#!/usr/bin/env python3
"""Pin the derive expression layer's semantics oracle: MEASURE DuckDB
(the authoritative ecosystem reference for data-type semantics) and emit
docs/derive-expr-pins.md as ground truth for the seine_rs.derive
expression layer (with_columns / filter). Values below are MEASURED,
not assumed — rerun and diff on any oracle version bump.

The pinned version is asserted hard: the differential battery
(bindings/tests/test_derive_expr.py) compares three evaluators — the
Rust kernels, a pure-python reference, and DuckDB SQL — and version
drift in the oracle must be loud, not silent.

Run: .venv/bin/python tools/pin_derive_expr.py > docs/derive-expr-pins.md
"""
import duckdb

assert duckdb.__version__ == "1.5.4", (
    f"derive-expr pins are measured against duckdb 1.5.4; found "
    f"{duckdb.__version__} — re-measure, diff the pins doc, and update "
    f"this assert deliberately"
)

con = duckdb.connect()


def scalar(sql):
    """One SELECT scalar; errors are values here (the pins record WHAT
    errors, since the expression layer maps oracle errors to its own
    loud errors)."""
    try:
        r = con.sql(f"SELECT {sql}").fetchall()[0][0]
        return "NULL" if r is None else repr(r)
    except Exception as e:  # duckdb.Error subclasses vary; first line only
        return f"ERROR: {str(e).splitlines()[0]}"


out = []


def emit(s=""):
    out.append(s)


def table(title, exprs):
    emit(f"## {title}")
    emit()
    emit("| expression | result |")
    emit("|---|---|")
    for e in exprs:
        emit(f"| `{e}` | {scalar(e)} |")
    emit()


emit(f"# Derive expression-layer semantics pins (oracle: duckdb {duckdb.__version__})")
emit()
emit("Generated by tools/pin_derive_expr.py — the measured ground truth")
emit("behind seine_rs.derive's expression layer (with_columns / filter)")
emit("and its pure-python reference evaluator. Regenerate and diff on any")
emit("oracle version bump. All BIGINT literals are cast explicitly: bare")
emit("integer literals in DuckDB are INT32 and change overflow behavior.")
emit()
emit("**The decision rule** (on the record): measured DuckDB behavior wins")
emit("on VALUE semantics (rem signs, rounding direction, Kleene tables,")
emit("CASE-null); the house loud-error doctrine wins on ERROR policy")
emit("(integer overflow, division by zero, failed casts are loud errors in")
emit("the kernels, never silent null manufacture — where DuckDB errors too,")
emit("the fuzzer treats both as matching error outcomes); IEEE-754 wins on")
emit("float specials (NaN/inf are VALUES; x/0.0 is ±inf; NaN != NaN). Every")
emit("deliberate divergence from the oracle lives in the ledger at the")
emit("bottom of this file.")
emit()

B = "CAST({} AS BIGINT)".format
D = "CAST({} AS DOUBLE)".format

table("A. Integer division, floor division, remainder (signs)", [
    f"{B(7)} / {B(2)}",
    f"{B(-7)} / {B(2)}",
    f"typeof({B(7)} / {B(2)})",
    f"{B(7)} // {B(2)}",
    f"{B(-7)} // {B(2)}",
    f"{B(7)} // {B(-2)}",
    f"{B(-7)} // {B(-2)}",
    f"typeof({B(7)} // {B(2)})",
    f"{B(7)} % {B(3)}",
    f"{B(-7)} % {B(3)}",
    f"{B(7)} % {B(-3)}",
    f"{B(-7)} % {B(-3)}",
    f"{D(7.5)} % {D(3.0)}",
    f"{D(-7.5)} % {D(3.0)}",
    f"{D(7.5)} // {D(2.0)}",
    f"{D(-7.5)} // {D(2.0)}",
    f"typeof({D(7.5)} // {D(2.0)})",
])

table("B. Division / remainder by zero", [
    f"{B(1)} / {B(0)}",
    f"{B(1)} // {B(0)}",
    f"{B(1)} % {B(0)}",
    f"{D(1.0)} / {D(0.0)}",
    f"{D(-1.0)} / {D(0.0)}",
    f"{D(0.0)} / {D(0.0)}",
    f"{D(1.0)} % {D(0.0)}",
])

MAX, MIN = 9223372036854775807, -9223372036854775808
table("C. BIGINT overflow edges", [
    f"{B(MAX)} + {B(1)}",
    f"{B(MAX)} * {B(2)}",
    f"{B(MIN)} - {B(1)}",
    f"-({B(MIN)})",
    f"{B(MIN)} // {B(-1)}",
    f"{B(MIN)} % {B(-1)}",
    f"abs({B(MIN)})",
])

table("D. DOUBLE -> BIGINT casts (rounding direction, overflow, specials)", [
    f"CAST({D(2.5)} AS BIGINT)",
    f"CAST({D(3.5)} AS BIGINT)",
    f"CAST({D(-2.5)} AS BIGINT)",
    f"CAST({D(2.4)} AS BIGINT)",
    f"CAST({D(2.6)} AS BIGINT)",
    f"CAST({D(-2.6)} AS BIGINT)",
    f"CAST({D('1e300')} AS BIGINT)",
    f"CAST(CAST('NaN' AS DOUBLE) AS BIGINT)",
    f"CAST(CAST('Infinity' AS DOUBLE) AS BIGINT)",
    f"CAST({B(5)} AS DOUBLE)",
])

table("E. round() (half cases, ndigits, negative ndigits)", [
    f"round({D(2.5)})",
    f"round({D(3.5)})",
    f"round({D(-2.5)})",
    f"round({D(0.5)})",
    f"round({D(2.345)}, 2)",
    f"round({D(2.675)}, 2)",
    f"round({D(1234.5)}, -2)",
    f"round({D(1250.0)}, -2)",
    f"typeof(round({D(2.5)}))",
    f"round({B(7)})",
    # fp-tie forensics: 2.675 is REALLY 2.67499999999999982... — what
    # DuckDB does with such ties decides the kernel's implementation
    f"round({D(2.665)}, 2)",
    f"round({D(2.685)}, 2)",
    f"round({D(0.125)}, 2)",
    f"round({D(0.135)}, 2)",
    f"round({D(-2.675)}, 2)",
])

table("F. floor / ceil / sqrt / pow", [
    f"floor({D(2.5)})",
    f"floor({D(-2.5)})",
    f"ceil({D(2.5)})",
    f"ceil({D(-2.5)})",
    f"typeof(floor({D(2.5)}))",
    f"sqrt({D(-1.0)})",
    f"sqrt({D(0.0)})",
    f"pow({B(2)}, {B(10)})",
    f"typeof(pow({B(2)}, {B(10)}))",
    f"pow({D(2.0)}, {D(-1.0)})",
    f"pow({D(0.0)}, {D(0.0)})",
])

table("G. CASE with a NULL condition (if_else semantics)", [
    "CASE WHEN CAST(NULL AS BOOLEAN) THEN 'then' ELSE 'else' END",
    "CASE WHEN TRUE THEN 'then' ELSE 'else' END",
    "CASE WHEN FALSE THEN 'then' ELSE 'else' END",
])

table("H. String ops x NULL", [
    "'a' || CAST(NULL AS VARCHAR)",
    "concat('a', CAST(NULL AS VARCHAR))",
    "contains(CAST(NULL AS VARCHAR), 'a')",
    "contains('abc', CAST(NULL AS VARCHAR))",
    "starts_with(CAST(NULL AS VARCHAR), 'a')",
    "ends_with('abc', CAST(NULL AS VARCHAR))",
    "length(CAST(NULL AS VARCHAR))",
    "typeof(length('abc'))",
    "'b' < 'a'",
    "'B' < 'a'",
])

table("I. Comparisons x NULL (the derive registry's six)", [
    "CAST(NULL AS BIGINT) = 1",
    "CAST(NULL AS BIGINT) <> 1",
    "CAST(NULL AS BIGINT) < 1",
    "CAST(NULL AS BIGINT) <= 1",
    "CAST(NULL AS BIGINT) > 1",
    "CAST(NULL AS BIGINT) >= 1",
    "CAST(NULL AS BIGINT) = CAST(NULL AS BIGINT)",
])

emit("## J. Kleene connectives (locality re-emit; full tables in duckdb-datatype-pins.md)")
emit()
emit("| a | b | a AND b | a OR b |")
emit("|---|---|---|---|")
for a in ["TRUE", "FALSE", "NULL"]:
    for b in ["TRUE", "FALSE", "NULL"]:
        emit(f"| {a} | {b} | {scalar(f'{a} AND {b}')} | {scalar(f'{a} OR {b}')} |")
emit()

table("K. Float specials as DuckDB sees them (ledger inputs)", [
    "CAST('NaN' AS DOUBLE) = CAST('NaN' AS DOUBLE)",
    "CAST('NaN' AS DOUBLE) < CAST('Infinity' AS DOUBLE)",
    "CAST('Infinity' AS DOUBLE) + {}".format(D(1.0)),
    "CAST('NaN' AS DOUBLE) + {}".format(D(1.0)),
])

emit("## L. WHERE with a NULL predicate (filter() semantics)")
emit()
con.sql("CREATE OR REPLACE TABLE t_w(v BIGINT)")
con.sql("INSERT INTO t_w VALUES (1), (NULL), (5)")
rows = [r[0] for r in con.sql("SELECT v FROM t_w WHERE v > 2").fetchall()]
emit(f"- `t_w(v) = [1, NULL, 5]`; `WHERE v > 2` -> rows: {rows}")
emit("  (NULL predicate rows DROP — derive.filter matches this.)")
emit()

emit("## The divergence ledger (deliberate, on the record)")
emit()
emit("| # | surface | oracle (measured above) | the kernels | why |")
emit("|---|---|---|---|---|")
emit("| 1 | float NaN comparisons | NaN = NaN is TRUE (value/total order) | IEEE: NaN != NaN | floats follow IEEE-754 end to end; DuckDB's NaN-as-orderable-value is a SQL convention the dataframe world does not share. The fuzzer's IEEE side-battery excludes DuckDB. |")
emit("| 2 | `%` vs Python | sign of DIVIDEND (C semantics) | same as oracle | divergence is from PYTHON'S floored `%`, documented in the docstring; the oracle and kernels agree. |")
emit("| 3 | `round` vs Python | half AWAY FROM ZERO | same as oracle | divergence is from Python's banker's rounding, documented in the docstring; oracle and kernels agree (and match the shipped haversine kernel). |")
emit("| 4 | error policy | (see B/C: what errors vs what yields NULL) | int overflow / div0 / failed cast are ALWAYS loud errors | the house doctrine: silent null manufacture is corruption; where the oracle errors too the fuzzer matches error-to-error, where it yields a value the pin above is the spec. |")
emit("| 5 | string concat builtin | `concat()` skips NULLs | kernels use `\\|\\|` semantics (null propagates) | the battery's SQL translation uses `\\|\\|`, never `concat()`. |")
emit("| 6 | `//` `%` by zero (int) | NULL (section B) | loud error | ledger row 4's policy applied; the battery maps oracle-NULL-on-zero-divisor to the kernels' error for these two ops. |")
emit("| 7 | `//` on DOUBLE | plain division (7.5 // 2.0 = 3.75, section A) | `//` is INTEGER-ONLY — a float operand is a loud type error steering to `/` + `.floor()` | DuckDB's float `//` quirk answers no user question; restricting the operator keeps it honest. On the integer domain kernels and oracle agree (truncation; C-family div/mod identity with `%`). Python's FLOORED `//` divergence is documented in the docstring. |")
emit("| 8 | `round(x, n)` algorithm | rounds the SHORTEST-DECIMAL representation half-away (2.675 -> 2.68 though the binary value is 2.67499...; all fp-tie forensics in section E consistent) | same, by construction | kernels + pure-python reference both implement shortest-roundtrip-decimal rounding (Rust fmt / Python repr are both shortest-roundtrip); agrees with f64::round half-away at n=0, so the shipped haversine kernel's rounding is unchanged. |")
emit("| 9 | `if_else`/`fill_null` branch evaluation | SQL CASE is LAZY (an error in the untaken branch never surfaces) | EAGER — both branches evaluate vectorized over every row; a row-level error (div0, overflow) in either branch errors the batch even where that branch is not selected | dataframe-engine reality (polars behaves the same); the battery accepts oracle-ok/kernel-div0-error for exactly this class. Guard divisors before dividing. |")
emit("| 10 | float comparison semantics | NaN equals itself and sorts LAST (NaN = NaN TRUE, NaN < inf FALSE — section K); ±0 equal | STANDARD IEEE via native f64 operators: NaN != everything including itself; -0.0 == 0.0 | the arrow cmp kernels use totalOrder (-0.0 != 0.0, NaN == NaN) and are NOT used for f64 — the kernels hand-roll IEEE, matching the oracle at ±0 and the published contract at NaN. The battery's IEEE side-battery (NaN/inf column data) excludes the oracle. |")
emit("| 11 | `i64::MIN % -1` | error (section C: overflow in division) | 0 (arrow's rem; mathematically exact — the overflow is an artifact of computing the quotient) | the fuzz pools carry no i64::MIN so the class is pinned by vector, not fuzzed. |")
emit()

print("\n".join(out))
