#!/usr/bin/env python3
"""D-096: pin the data-type oracle's semantics (SQL 3VL + DECIMAL) as
ground-truth tables. DuckDB is the authoritative reference for
ecosystem-facing data-type semantics per D-095 — this script GENERATES
the pins (docs/duckdb-datatype-pins.md); rerun after any oracle version
bump and diff.

Run: .venv/bin/python tools/pin_duckdb.py > docs/duckdb-datatype-pins.md
"""
import duckdb
import pyarrow as pa

con = duckdb.connect()
V = duckdb.__version__

def q(sql):
    return con.sql(sql).fetchall()

def scalar(sql):
    r = q(f"SELECT {sql}")[0][0]
    return "NULL" if r is None else str(r)

out = []
def emit(s=""):
    out.append(s)

emit(f"# DuckDB data-type semantics pins (oracle: duckdb {V}, pyarrow {pa.__version__})")
emit()
emit("Generated by tools/pin_duckdb.py — the D-095/D-096 ground truth for")
emit("the nulls (SQL 3VL) + exact-decimal features. Regenerate and diff on")
emit("any oracle version bump. Values below are MEASURED, not assumed.")
emit()

# ---------------------------------------------------------------- A
emit("## A. Comparison operators x NULL (all yield NULL = unknown)")
emit()
emit("| expression | result |")
emit("|---|---|")
for e in ["NULL = NULL", "NULL <> NULL", "1 = NULL", "NULL = 1", "NULL < 5",
          "NULL <= NULL", "NULL > 5", "NULL >= NULL",
          "NULL IS DISTINCT FROM NULL", "1 IS DISTINCT FROM NULL",
          "NULL IS NOT DISTINCT FROM NULL", "1 IS NOT DISTINCT FROM 1",
          "NULL IS NULL", "1 IS NULL", "NULL IS NOT NULL"]:
    emit(f"| `{e}` | {scalar(e)} |")
emit()

# ---------------------------------------------------------------- B
emit("## B. Boolean connectives (full 3VL tables)")
emit()
vals = ["TRUE", "FALSE", "NULL"]
emit("| a | b | a AND b | a OR b |")
emit("|---|---|---|---|")
for a in vals:
    for b in vals:
        emit(f"| {a} | {b} | {scalar(f'{a} AND {b}')} | {scalar(f'{a} OR {b}')} |")
emit()
emit("| a | NOT a |")
emit("|---|---|")
for a in vals:
    emit(f"| {a} | {scalar(f'NOT {a}')} |")
emit()

# ---------------------------------------------------------------- C
emit("## C. IN / NOT IN with NULLs")
emit()
emit("| expression | result |")
emit("|---|---|")
for e in ["NULL IN (1, 2)", "1 IN (1, NULL)", "3 IN (1, NULL)",
          "NULL IN (NULL)", "1 NOT IN (2, NULL)", "1 NOT IN (1, NULL)",
          "NULL NOT IN (1, 2)"]:
    emit(f"| `{e}` | {scalar(e)} |")
emit()

# ---------------------------------------------------------------- D
emit("## D. WHERE semantics: only TRUE passes (UNKNOWN filtered)")
emit()
con.sql("CREATE OR REPLACE TABLE t_where(v BIGINT)")
con.sql("INSERT INTO t_where VALUES (1), (NULL), (5)")
rows = q("SELECT v FROM t_where WHERE v > 2")
emit(f"- `t_where(v) = [1, NULL, 5]`; `WHERE v > 2` -> rows: {[r[0] for r in rows]}")
rows = q("SELECT v FROM t_where WHERE NOT (v > 2)")
emit(f"- `WHERE NOT (v > 2)` -> rows: {[r[0] for r in rows]} (NULL row excluded from BOTH — 3VL, not complement)")
emit()

# ---------------------------------------------------------------- E
emit("## E. String operators x NULL")
emit()
emit("| expression | result |")
emit("|---|---|")
for e in ["NULL LIKE 'a%'", "'abc' LIKE NULL",
          "contains('abc', NULL::VARCHAR)", "contains(NULL::VARCHAR, 'b')",
          "regexp_full_match(NULL::VARCHAR, 'a.*')", "regexp_full_match('abc', NULL::VARCHAR)"]:
    emit(f"| `{e}` | {scalar(e)} |")
emit()

# ---------------------------------------------------------------- F
emit("## F. Join semantics: NULL keys never equi-join")
emit()
con.sql("CREATE OR REPLACE TABLE jl(k BIGINT, tag VARCHAR)")
con.sql("CREATE OR REPLACE TABLE jr(k BIGINT, tag VARCHAR)")
con.sql("INSERT INTO jl VALUES (1,'l1'), (NULL,'lN')")
con.sql("INSERT INTO jr VALUES (1,'r1'), (NULL,'rN')")
rows = q("SELECT jl.tag, jr.tag FROM jl JOIN jr ON jl.k = jr.k ORDER BY 1")
emit(f"- `jl JOIN jr ON jl.k = jr.k` -> {rows} (the NULL-NULL pair does NOT join)")
rows = q("SELECT jl.tag, jr.tag FROM jl JOIN jr ON jl.k IS NOT DISTINCT FROM jr.k ORDER BY 1")
emit(f"- `... ON jl.k IS NOT DISTINCT FROM jr.k` -> {rows} (null-safe join for reference)")
emit()

# ---------------------------------------------------------------- G
emit("## G. Aggregates over NULLs / empty sets")
emit()
con.sql("CREATE OR REPLACE TABLE ag(v BIGINT)")
con.sql("INSERT INTO ag VALUES (1), (NULL), (3)")
emit("`ag(v) = [1, NULL, 3]`:")
emit()
emit("| aggregate | result |")
emit("|---|---|")
for a in ["sum(v)", "count(v)", "count(*)", "avg(v)", "min(v)", "max(v)"]:
    emit(f"| `{a}` | {q(f'SELECT {a} FROM ag')[0][0]} |")
con.sql("CREATE OR REPLACE TABLE agn(v BIGINT)")
con.sql("INSERT INTO agn VALUES (NULL), (NULL)")
emit()
emit("`agn(v) = [NULL, NULL]` (all-null):")
emit()
emit("| aggregate | result |")
emit("|---|---|")
for a in ["sum(v)", "count(v)", "count(*)", "avg(v)", "min(v)", "max(v)"]:
    r = q(f"SELECT {a} FROM agn")[0][0]
    emit(f"| `{a}` | {'NULL' if r is None else r} |")
con.sql("CREATE OR REPLACE TABLE age(v BIGINT)")
emit()
emit("`age(v)` empty:")
emit()
emit("| aggregate | result |")
emit("|---|---|")
for a in ["sum(v)", "count(v)", "count(*)", "avg(v)", "min(v)", "max(v)"]:
    r = q(f"SELECT {a} FROM age")[0][0]
    emit(f"| `{a}` | {'NULL' if r is None else r} |")
emit()

# ---------------------------------------------------------------- H
emit("## H. Grouping / DISTINCT: NULLs are ONE group (TMS-key relevance)")
emit()
rows = q("SELECT v, count(*) FROM ag GROUP BY v ORDER BY v NULLS LAST")
emit(f"- `GROUP BY v` over [1, NULL, 3] -> {rows}")
rows = q("SELECT DISTINCT v FROM (VALUES (NULL), (NULL), (1)) t(v) ORDER BY v NULLS LAST")
emit(f"- `DISTINCT` over [NULL, NULL, 1] -> {[r[0] for r in rows]} (nulls collapse)")
emit()

# ---------------------------------------------------------------- I
emit("## I. DOUBLE NaN (the ingest-normalization rationale)")
emit()
emit("| expression | result |")
emit("|---|---|")
for e in ["'NaN'::DOUBLE = 'NaN'::DOUBLE", "'NaN'::DOUBLE > 1e308",
          "'NaN'::DOUBLE = NULL", "isnan('NaN'::DOUBLE)"]:
    emit(f"| `{e}` | {scalar(e)} |")
emit()
emit("DuckDB treats NaN as a VALUE (equal to itself, sorts greatest) — one")
emit("more reason pandas-NaN normalizes to NULL at the Seine boundary for")
emit("nullable float fields rather than leaking IEEE semantics into 3VL.")
emit()

# ---------------------------------------------------------------- J
emit("## J. DECIMAL semantics")
emit()
emit("| expression | result | note |")
emit("|---|---|---|")
checks = [
    ("typeof(1.23)", "SQL decimal literal type"),
    ("typeof(1.23::DECIMAL(18,3))", "explicit cast"),
    ("1.10::DECIMAL(3,2) = 1.1::DECIMAL(2,1)", "cross-scale value equality"),
    ("1.10::DECIMAL(3,2) = 1", "decimal vs integer"),
    ("0.1::DECIMAL(2,1) + 0.2::DECIMAL(2,1)", "exact addition (no 0.30000000000000004)"),
    ("typeof(0.1::DECIMAL(2,1) + 0.2::DECIMAL(2,1))", "addition result type"),
    ("typeof(1.5::DECIMAL(2,1) * 2.5::DECIMAL(2,1))", "multiplication result type"),
    ("1.005::DECIMAL(18,3)::DECIMAL(18,2)", "scale-reduction rounding"),
    ("1.015::DECIMAL(18,3)::DECIMAL(18,2)", "scale-reduction rounding (odd)"),
    ("(-1.005)::DECIMAL(18,3)::DECIMAL(18,2)", "negative rounding"),
    ("0.1::DECIMAL(2,1) = 0.1::DOUBLE", "decimal vs double compare"),
    ("typeof(sum(x)) FROM (VALUES (1.25::DECIMAL(10,2))) t(x)", "SUM result type"),
    ("typeof(avg(x)) FROM (VALUES (1.25::DECIMAL(10,2))) t(x)", "AVG result type"),
    ("typeof(min(x)) FROM (VALUES (1.25::DECIMAL(10,2))) t(x)", "MIN result type"),
    ("sum(x) FROM (VALUES (0.1::DECIMAL(2,1)),(0.2::DECIMAL(2,1)),(0.3::DECIMAL(2,1))) t(x)", "exact SUM"),
    ("avg(x) FROM (VALUES (1::DECIMAL(2,0)),(2::DECIMAL(2,0))) t(x)", "AVG value"),
]
for e, note in checks:
    try:
        r = scalar(e)
    except Exception as ex:
        r = f"ERROR: {str(ex).splitlines()[0][:70]}"
    emit(f"| `{e}` | {r} | {note} |")
emit()
emit("Overflow behavior:")
for e in ["99.99::DECIMAL(4,2) + 99.99::DECIMAL(4,2)",
          "(9.9::DECIMAL(2,1) * 9.9::DECIMAL(2,1))::DECIMAL(2,1)"]:
    try:
        r = scalar(e)
    except Exception as ex:
        r = f"ERROR: {str(ex).splitlines()[0][:90]}"
    emit(f"- `{e}` -> {r}")
emit()

# ---------------------------------------------------------------- K
emit("## K. Arrow round-trip (ingestion boundary)")
emit()
tbl = pa.table({
    "d": pa.array([None, "1.25", "-3.50"], type=pa.string()).cast(pa.decimal128(10, 2)),
    "f": pa.array([1.5, None, float("nan")], type=pa.float64()),
    "i": pa.array([1, None, 3], type=pa.int64()),
})
con.register("arrow_tbl", tbl)
emit(f"- pyarrow schema: `{tbl.schema}`".replace("\n", "; "))
rows = q("SELECT typeof(d), typeof(f), typeof(i) FROM arrow_tbl LIMIT 1")
emit(f"- DuckDB sees types: {rows[0]}")
rows = q("SELECT d, f, i, d IS NULL, isnan(f) FROM arrow_tbl")
emit(f"- values (d, f, i, d IS NULL, isnan(f)): {rows}")
emit("- Arrow validity-null arrives as SQL NULL; Arrow float NaN arrives as")
emit("  NaN (a value) — the Seine boundary normalizes NaN -> NULL for")
emit("  NULLABLE float fields per D-095 (and keeps rejecting NaN-as-null")
emit("  confusion for non-nullable ones).")

print("\n".join(out))
